// Define color
uint16_t green = matrix.Color(0, 255, 0);
uint16_t black = matrix.Color(0, 0, 0);


// Define the pixel data

const uint16_t alien[44][11] = {
  { black, black, black, black, green, green, green, black, black, black, black },
  { black, black, green, green, green, green, green, green, green, black, black },
  { black, green, green, green, green, green, green, green, green, green, black },
  { green, green, black, black, green, green, green, black, black, green, green },
  { green, green, black, black, green, green, green, black, black, green, green },
  { green, green, green, green, green, green, green, green, green, green, green },
  { green, green, green, green, green, green, green, green, green, green, green },
  { black, green, green, black, green, green, green, black, green, green, black },
  { black, black, green, green, black, black, black, green, green, black, black },
  { black, black, black, green, green, green, green, green, black, black, black },
  { black, black, black, black, green, green, green, black, black, black, black },
  { black, black, black, black, black, green, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
  { black, black, black, black, black, black, black, black, black, black, black },
};
